version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: trading-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redpanda:
    image: redpandadata/redpanda:v23.2.14
    container_name: trading-redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --pandaproxy-addr=PLAINTEXT://0.0.0.0:8082,OUTSIDE://0.0.0.0:8083
      - --advertise-pandaproxy-addr=PLAINTEXT://localhost:8082,OUTSIDE://localhost:8083
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092,OUTSIDE://localhost:9093
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=localhost:33145
    ports:
      - "9092:9092" # Kafka API
      - "9093:9093" # Kafka API (External)
      - "8081:8081" # Schema Registry
      - "8082:8082" # HTTP Proxy
      - "8083:8083" # HTTP Proxy (External)
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: redpandadata/console:v2.3.1
    container_name: trading-redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      - REDPANDA_BROKERS=redpanda:9092
      - KAFKA_BROKERS=redpanda:9092

  redpanda-setup:
    image: redpandadata/redpanda:v23.2.14
    container_name: trading-redpanda-setup
    depends_on:
      - redpanda
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo 'Waiting for Redpanda to be ready...' &&
      sleep 10 &&
      echo 'Creating Kafka topics...' &&
      rpk topic create --brokers=redpanda:9092 origination.account &&
      rpk topic create --brokers=redpanda:9092 partnerconsumer.deposit &&
      rpk topic create --brokers=redpanda:9092 partnerconsumer.order &&
      echo 'Kafka topics created!'

  migrations:
    image: migrate/migrate:v4.15.2
    container_name: trading-migrations
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=trading
    command: ["-path=/migrations", "-database", "postgres://postgres:postgres@postgres:5432/trading?sslmode=disable", "up"]

volumes:
  postgres-data:
